[pytest]
testpaths = tests
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
addopts =
    -s
    --tb=short
    --strict-markers
    --disable-warnings
    ; --headed （本地开发时可取消注释以查看浏览器界面）
    --browser chromium
    --alluredir=reports/allure-results
    
    ; ===在 conftest.py 中已经实现了失败填充截图和视频所以不需要在这里写了
    ; --screenshot=only-on-failure 
    ; --video=retain-on-failure

    ; ==自己实现了不需要在这里配置了
    ; --base-url=http://localhost:3100
markers =
    ui: UI automation tests
    api: API automation tests
    smoke: Smoke tests
    regression: Regression tests
    performance: Performance tests